name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc \
            make \
            clang-format \
            clang-tidy \
            cppcheck

      - name: Clang-format
        run: make check-format

      - name: Clang-tidy
        run: make check-tidy

      - name: Cppcheck
        run: make check-cppcheck

      - name: Build
        run: make

      - name: Build com sanitizers
        run: make sanitize
